org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.home=C:\\Program Files\\Java\\jdk-25

minecraft_version=26.2
loader_version=0.19.3
fabric_api_version=0.154.0+26.2
cloth_config_version=26.1.154
mod_menu_version=20.0.0-beta.4
mod_version=4.0.0+mc26.2

mod_version=4.0.0+mc26.2
maven_group=com.ritesh
archives_base_name=BetterMaceSwap
